baseURL = 'https://techeca.github.io/MiBew'
languageCode = 'en-us'
title = 'MiBew'
theme = "gokarna"
enableEmoji = true
# Automatically generate robots.txt
enableRobotsTXT = true

[params]
    # URL for the avatar on homepage
    avatarURL = "/images/horrible.png"

    # Description to display on homepage
    description = "Mejor lo voy anotar, después se me olvida"

    # You can use this to inject any HTML in the <head> tag.
    # Ideal usecase for this is to import custom js/css or add your analytics snippet
    customHeadHTML = '''
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    '''

    # Keywords relevant for SEO
    metaKeywords = ["blog", "gokarna", "hugo", "hola", "mundo", "ggwp"]

    # Footer text
    footer = "MiBew"

    # Show post in homepage
    showPostsOnHomePage = "recent"
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false
[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Posts"
    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 2


  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 3

    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
